---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-app
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: k8s.<ENV-NAME>-user-<ENV-USER-ID>-01.<ENV-ANIMAL>.commandemy.training
    http:
      paths:
      - backend:
          serviceName: flask-app
          servicePort: 80
